// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'customSearchContainer': string;
  'filterMenuContainer': string;
  'filteredMessage': string;
  'searchButton': string;
  'searchContainer': string;
  'searchInput': string;
}
export const cssExports: CssExports;
export default cssExports;
